import postgres from "npm:postgres@3.4.5";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-seed-secret"
};

interface SeedRow {
  category: string;
  category_order: number;
  category_position: number;
  global_position: number;
  english_word: string;
  spanish_word: string;
  catalan_word: string;
  english_phrase: string;
  spanish_phrase: string;
  catalan_phrase: string;
  published_to?: string;
}

function jsonResponse(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: {
      ...CORS_HEADERS,
      "Content-Type": "application/json"
    }
  });
}

function getDatabaseUrl(): string {
  const connectionString = (Deno.env.get("DATABASE_POOLER_URL") ?? "").trim();
  if (!connectionString) {
    throw new Error("Missing DATABASE_POOLER_URL secret.");
  }
  return connectionString;
}

Deno.serve(async (request) => {
  if (request.method === "OPTIONS") {
    return new Response("ok", { headers: CORS_HEADERS });
  }

  if (request.method !== "POST") {
    return jsonResponse({ error: "Method not allowed" }, 405);
  }

  const expectedSecret = (Deno.env.get("TOKEN_ROTATION_SECRET") ?? "").trim();
  const providedSecret = (request.headers.get("x-seed-secret") ?? "").trim();
  if (!expectedSecret || providedSecret !== expectedSecret) {
    return jsonResponse({ error: "Unauthorized" }, 401);
  }

  const body = (await request.json()) as { rows?: SeedRow[] };
  const rows = body.rows ?? [];
  if (!Array.isArray(rows) || rows.length === 0) {
    return jsonResponse({ error: "Missing rows payload." }, 400);
  }

  const sql = postgres(getDatabaseUrl(), {
    ssl: "require",
    prepare: false,
    max: 1,
    idle_timeout: 5
  });

  try {
    await sql.begin(async (tx) => {
      await tx`
        create table if not exists public.language_words (
          id bigint generated by default as identity primary key,
          created_at timestamptz default now() not null,
          category text not null,
          category_order integer not null,
          category_position integer not null,
          global_position integer not null unique,
          english_word text not null,
          spanish_word text not null,
          catalan_word text not null,
          english_phrase text not null,
          spanish_phrase text not null,
          catalan_phrase text not null,
          published_to text not null default ''
        )
      `;

      await tx`create index if not exists language_words_category_order_idx on public.language_words (category_order, category_position)`;
      await tx`create index if not exists language_words_category_idx on public.language_words (category)`;
      await tx`alter table public.language_words enable row level security`;
      await tx`drop policy if exists language_words_select on public.language_words`;
      await tx`
        create policy language_words_select
          on public.language_words
          for select
          to anon
          using (true)
      `;

      const values = rows.map((row) => ({
        category: row.category,
        category_order: row.category_order,
        category_position: row.category_position,
        global_position: row.global_position,
        english_word: row.english_word,
        spanish_word: row.spanish_word,
        catalan_word: row.catalan_word,
        english_phrase: row.english_phrase,
        spanish_phrase: row.spanish_phrase,
        catalan_phrase: row.catalan_phrase,
        published_to: row.published_to ?? ""
      }));

      await tx`
        insert into public.language_words ${tx(values, "category", "category_order", "category_position", "global_position", "english_word", "spanish_word", "catalan_word", "english_phrase", "spanish_phrase", "catalan_phrase", "published_to")}
        on conflict (global_position) do update set
          category = excluded.category,
          category_order = excluded.category_order,
          category_position = excluded.category_position,
          english_word = excluded.english_word,
          spanish_word = excluded.spanish_word,
          catalan_word = excluded.catalan_word,
          english_phrase = excluded.english_phrase,
          spanish_phrase = excluded.spanish_phrase,
          catalan_phrase = excluded.catalan_phrase,
          published_to = excluded.published_to
      `;
    });

    return jsonResponse({ ok: true, inserted: rows.length });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown seed error";
    return jsonResponse({ error: message }, 500);
  } finally {
    await sql.end({ timeout: 5 }).catch(() => undefined);
  }
});
